### ISSUE TITLE
Can't get LinkPreview for 3.3.3 working

### ISSUE THREAD

**Issue by rothnorton** [wireapp/lithium#59] opened 2022-02-05 04:56 UTC
Updated to latest lithium 3.3.3

Can't get linkpreview working anymore (previously on assets v1 (3.0.x) i think).  

Code is:
 //get a xenon Picture using byte[] and mimetype after retrieving content using Jsoup
Picture previewImage = getLinkPreviewImage(previewImageUrl);

final AssetKey assetKey = client.uploadAsset(previewImage);
previewImage.setAssetKey(assetKey.id);
previewImage.setAssetToken(assetKey.token);

LinkPreview preview = new LinkPreview(previewUrl,  previewTitle,  previewImage);
client.send(preview);

Link preview posts but image is just grey square.
Have debugged and Picture seems to be created alright, so wondering if its in the upload asset process, ie my code isnt quite right.

**Comment by dkovacevic** [comment] 2022-02-10 12:39
I have a feeling the problem is in the Picture class. isPublic property is always False but previews should be public.
I put getter and setter in xenon 1.3.5.
Does it help if you try:
```
previewImage.setPublic(true);
```
inside getLinkPreviewImage
?

**Comment by rothnorton** [comment] 2022-02-10 22:58
Sorry, i hadn't run it debug mode earlier (as wasn't set up on host).

So the value of assetKey after calling this:
final AssetKey assetKey = client.uploadAsset(previewImage);

without the setPublic(true) on the Picture
assetKey.id is null
assetKey.token is a proper value

after setPublic(true)
assetKey.id is null
assetKey.token is also null

Still grey image obviously.

apologies for not noticing that earlier.

**Comment by dkovacevic** [comment] 2022-11-23 06:45
We had problems with set key and token for assets. This should be fixed in 3.4.5.
Sorry for the late response :'(

**Closed by dkovacevic** 2022-11-23 06:45 UTC
